public inherited sharing class Sales_Constants {
    //Adding constants for LockOpportunityTriggerHelper class
    public static final string OPP_IR_STATUS_PSTLS = 'Pending - Send to Local (Self)';
    public static final string OPP_IR_STATUS_PSTLRR = 'Pending - Send to Local (Round-Robin)';
    public static final string OPP_IR_STATUS_ETL = 'Extracted to Local';
    public static final string OPP_IR_STATUS_UFL = 'Updated from Local';
    public static final string OPP_IR_STATUS_CAOC = 'Closed – Auto Opportunity Created';
    public static final string OPP_IR_STATUS_LOL = 'Loaded to Local';
    
    //1084 Updated Opp Stages
    public static final string OPP_STAGE_CW = 'Closed Won';
    public static final string OPP_STAGE_CL = 'Closed Lost';

    // Constants for Contact Trigger
    public static final String USER_ELOQUA_FIRST_NAME = 'Eloqua';
    public static final String USER_ELOQUA_LAST_NAME = 'Integration';
}
